######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 16 00:06:42 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Crypto.h
SOURCES += Crypto.cpp Crypto_client.cpp
